ClusterCommsPort: 3001
CardanoContainer: nessusio/cardano-node
NumberOfRelays: 2

RelayMemoryRequest: 2048Mi
RelayMemoryLimit: 8192Mi
RelayCpuRequest: 2
RelayCpuLimit: 4
RelayStorageRequest: 10Gi

BlockProducerMemoryRequest: 2048Mi
BlockProducerMemoryLimit: 8192Mi
BlockProducerCpuRequest: 2
BlockProducerCpuLimit: 4
BlockProducerStorageRequest: 30Gi