apiVersion: v1
kind: Service
metadata:
  name: block-producer
  labels: 
    {{- include "block-producer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "block-producer.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.ClusterCommsPort }}
      targetPort: {{ .Values.ClusterCommsPort }}
      name: cluster-comms