apiVersion: v1
kind: Secret
metadata:
  name: block-producer-keys
  labels:
    {{- include "block-producer.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "keys/*").AsSecrets | indent 2 }}