apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-producer-keys-claim
  labels: 
    {{- include "block-producer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi ## cloud providers typically offer 1Gi as the smallest volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-producer-data-claim
  labels: 
    {{- include "block-producer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.BlockProducerStorageRequest }}