apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-producer-keys-claim
  labels: 
    {{- include "block-producer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-producer-data-claim
  labels: 
    {{- include "relay.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.BlockProducerStorageRequest }}