apiVersion: v1
kind: Service
metadata:
  name: block-producer
  labels: 
    group: block-producer
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: block-producer
  ports:
    - port: {{ .Values.ClusterCommsPort }}
      targetPort: {{ .Values.ClusterCommsPort }}
      name: cluster-comms