apiVersion: v1
kind: Pod
metadata:
  name: block-producer
  labels:
    {{- include "block-producer.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/block-producer-configmap.yaml") . | sha256sum }}
spec:
  volumes:
    - name: block-producer-data
      persistentVolumeClaim:
        claimName: block-producer-data-claim
    - name: block-producer-keys
      persistentVolumeClaim:
        claimName: block-producer-keys-claim
    - name: keys
      secret:
        secretName: block-producer-keys
  initContainers:
    - name: init-keys ## We use this container to copy the keys from secret ro storage to rw storage
      image: busybox:latest
      command: ['sh', '-c', "echo 'Copying keys from secrets in to writable location'; cp /secret-keys/* /writable-keys"]
      volumeMounts:
        - mountPath: /secret-keys
          name: keys
        - mountPath: /writable-keys
          name: block-producer-keys
  containers:
    - name: block-producer
      image: {{ include "cardano.container" . }}
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: {{ .Values.CpuMemoryRequest }}
          cpu: {{ .Values.CpuCpuRequest }}
        limits:
          memory: {{ .Values.CpuMemoryLimit }}
          cpu: {{ .Values.CpuCpuLimit }}
      args: ["run"]
      volumeMounts:
        - mountPath: /opt/cardano/data
          name: block-producer-data
        - mountPath: /var/cardano/config/keys
          name: block-producer-keys
      ports:
        - containerPort: {{ .Values.ClusterCommsPort }}
          name: cluster-comms
      envFrom:
        - configMapRef:
            name: block-producer