apiVersion: v1
kind: ConfigMap
metadata:
  name: block-producer-configmap
  labels: 
    group: block-producer
data:
  CARDANO_TOPOLOGY: |
    {
      "Producers": [
        {
          "addr": "internal-relays.{{ .Release.Namespace }}.svc.cluster.local",
          "port": {{ .Values.ClusterCommsPort }},
          "valency": {{ .Values.NumberOfRelays }}
        }
      ]
    }
  CARDANO_BLOCK_PRODUCER: "true"