apiVersion: v1
kind: ConfigMap
metadata:
  name: block-producer-configmap
data:
  CARDANO_TOPOLOGY: |
    {
      "Producers": [
        {
          "addr": "internal-relays.default.svc.cluster.local",
          "port": {{ .Values.ClusterCommsPort }},
          "valency": {{ .Values.NumberOfRelays }}
        }
      ]
    }
  CARDANO_BLOCK_PRODUCER: "true"