apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels: 
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'cardano' # To scrape data from the cardano node
        scrape_interval: 5s
        static_configs:
          - targets: ['block-producer.{{ .Release.Namespace }}.svc.cluster.local:12798']