apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/prometheus-configmap.yaml") . | sha256sum }}
spec:
  containers:
    - name: prometheus
      image: {{ .Values.PrometheusContainer }}
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: {{ .Values.PrometheusMemoryRequest }}
          cpu: {{ .Values.PrometheusCpuRequest }}
        limits:
          memory: {{ .Values.PrometheusMemoryLimit }}
          cpu: {{ .Values.PrometheusCpuLimit }}
      volumeMounts:
      - name: promethues-config
        mountPath: "/etc/prometheus"
        readOnly: true
  volumes:
  - name: promethues-config
    configMap:
      name: prometheus