apiVersion: v1
kind: Service
metadata:
  name: internal-relays
  labels: 
    group: relays
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: relay
  ports:
    - port: {{ .Values.ClusterCommsPort }}
      targetPort: {{ .Values.ClusterCommsPort }}
      name: cluster-comms