apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: relay
  labels: 
    {{- include "relay.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "relay.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0 ## allow internet traffic to connect to the relay
    ports:
    - protocol: TCP
      port: {{ .Values.ClusterCommsPort }}
  egress:
  - {}