apiVersion: v1
kind: Service
metadata:
  name: internal-relays
  labels: 
    {{- include "relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.ClusterCommsPort }}
      targetPort: {{ .Values.ClusterCommsPort }}
      name: cluster-comms